apps/rails-app/config/routes.rb
Rails.application.routes.draw do
  get  "sign_in", to: "sessions#new"
  get  "sign_up", to: "registrations#new"
  namespace :two_factor_authentication do
    namespace :challenge do
      resource :totp,           only: [ :new, :create ]
      resource :recovery_codes, only: [ :new, :create ]
    end
    namespace :profile do
      resource  :totp,           only: [ :new, :create, :update ]
      resources :recovery_codes, only: [ :index, :create ]
    end
  end
  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"
  namespace :sessions do
    resource :passwordless, only: [ :new, :edit, :create ]
  end
  resource :invitation, only: [ :new, :create ]
  root "home#index"
  post "sign_in", to: "sessions#create"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end
  namespace :authentications do
    resources :events, only: :index
  end
  resource :session
  resources :passwords, param: :token
  mount RailsEventStore::Browser => "/res" if Rails.env.development?
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

apps/rails-app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

apps/rails-app/app/views/home/index.html.erb
<p style="color: green"><%= notice %></p>

<p>Signed as <%= Current.user.email %></p>

<h2>Login and verification</h2>

<div>
  <%= link_to "Change password", edit_password_path %>
</div>

<div>
  <%= link_to "Change email address", edit_identity_email_path %>
</div>

<div>
  <%= link_to "Two-Factor Authentication", new_two_factor_authentication_profile_totp_path %>
</div>

<% if Current.user.otp_required_for_sign_in? %>
  <div><%= link_to "Recovery Codes", two_factor_authentication_profile_recovery_codes_path %></div>
<% end %>

<div>
  <%= link_to "Send invitation", new_invitation_path %>
</div>

<h2>Access history</h2>

<div>
  <%= link_to "Devices & Sessions", sessions_path %>
</div>

<div>
  <%= link_to "Activity Log", authentications_events_path %>
</div>

<br>

<%= button_to "Log out", Current.session, method: :delete %>